apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: reversewords-app
  name: reverse-words
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reversewords-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reversewords-app
    spec:
      containers:
      - env:
        - name: RELEASE
          valueFrom:
            configMapKeyRef:
              key: release
              name: reversewords-release
        image: quay.io/mavazque/reversewords:c7da63545df513307ab7ddc02e797561402bee97
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 2
        name: reverse-words
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /reversewords-storage/
          name: reversewords-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: reversewordsapp
      serviceAccountName: reversewordsapp
      terminationGracePeriodSeconds: 30
      volumes:
      - name: reversewords-storage
        persistentVolumeClaim:
          claimName: reversewords-storage
