apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: reversewords-app
  name: reversewords-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: odf-lvm-vg1
  volumeMode: Filesystem
