apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  annotations:
  labels:
    app: reversewords-app
  name: pod-reader
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
