name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/mavazque/reversewords:${GITHUB_SHA}

    - name: save the image
      run: docker save -o /tmp/reverse.tar quay.io/mavazque/reversewords:${GITHUB_SHA}

    - name: Save container as artifact
      uses: actions/upload-artifact@v1
      with:
        name: reverse-image
        path: /tmp/reverse.tar

  deploy:
    name: Deploy kind and test
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install ./kubectl /usr/local/bin/
        kubectl version --short --client
    
    - name: install the kind binary
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind version
        
    - name: deploy kind cluster
      run: kind create cluster

    - name: deploy router crd
      run: kubectl apply -f https://raw.githubusercontent.com/konveyor/gitops-primer/main/hack/router-crd.yaml

    - name: pull the image from artifact
      uses: actions/download-artifact@v1
      with:
        name: reverse-image
        path: /tmp

    - name: Load the image
      run: docker load -i /tmp/reverse.tar

    - name: Load the image into kind
      run: kind load docker-image quay.io/mavazque/reversewords:${GITHUB_SHA}

    - name: test the image
      run: |
#        sed -i s/         image: quay.io/mavazque/reversewords:latest/         image: quay.io/mavazque/reversewords:${GITHUB_SHA}/g ./kube-objects/deployment.yaml
        sed -i "s|\(.*image:.*:\).*|\1${GITHUB_SHA}|" ./kube-objects/deployment.yaml
        kubectl apply -f ./kube-objects

    - name: verify 1 ready replica
      run: kubectl get deployment -n default -o jsonpath='{.status.readyReplicas}'

  push-image:
    name: Push image to quay
    needs: [ build, deploy ]
    if: >
      (github.event_name == 'push' || github.event_name == 'schedule') &&
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: pull artifact
        uses: actions/download-artifact@v1
        with:
          name: reverse-image
          path: /tmp

      - name: Load the image
        run: docker load -i /tmp/reverse.tar

      - name: push image
        run: docker push quay.io/mavazque/reversewords:${GITHUB_SHA}

  patch-deployment-file:
    name: patch the deployment and push
    needs: [ build, deploy, push-image ]
    runs-on: ubuntu-20.04
    if: >
      (github.event_name == 'push' || github.event_name == 'schedule') &&
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    steps:
       - uses: actions/checkout@v2
         with:
            path: kube-objects

       - name: patch the file
         run: |
           #sed -i s/         image: quay.io/mavazque/reversewords:latest/         image: quay.io/mavazque/reversewords:${GITHUB_SHA}/g kube-objects/kube-objects/deployment.yaml

       - name: Commit files
         run: |
             #cd kube-objects
             #git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
             #git config --local user.name "github-actions[bot]"
             #git commit -m "color changes" -a
             #git push -f
