name: Go App Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get Dependencies
      working-directory: ./go-code/
      run: go mod tidy
      
    - name: Run Linter
      uses: golangci/golangci-lint-action@v2
      with:
        working-directory: ./go-code/

    - name: Run Unit Tests
      working-directory: ./go-code/
      run: GOOS=linux GOARCH=amd64 go test -race -cover -v ./...

    - name: Run Build
      working-directory: ./go-code/
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o reverse-words-linux-amd64 -v ./...

    - name: Save app binary Artifact
      uses: actions/upload-artifact@v1
      with:
        name: reverse-words-linux-amd64
        path: ./go-code/reverse-words-linux-amd64

  release:
    name: Creates a new release with the resulting binary
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
    - name: Pull the app binary from Artifacts
      uses: actions/download-artifact@v1
      with:
        name: reverse-words-linux-amd64
        path: /tmp/
  
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/reverse-words-linux-amd64
        asset_name: reverse-words-linux-amd64
        tag: ${{ github.ref }}-release
        overwrite: true
        body: "Automatic release created by a GitHub Action"
