name: Go App Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      
    - name: Run Linter
      uses: golangci/golangci-lint-action@v2
      working-directory: ./go-code/

    - name: Get Dependencies
      working-directory: ./go-code/
      run: go mod tidy

    - name: Run Unit Tests
      working-directory: ./go-code/
      run: go test -v ./...

    - name: Run Build
      working-directory: ./go-code/
      run: go build -v ./...

