name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      
    - name: init
      working-directory: reverse-words
      run: go mod tidy
      
    - name: Build
      working-directory: reverse-words
      run: go build -v ./...

    - name: Test
      working-directory: reverse-words
      run: go test -v ./...
